name: Prediccion Diaria MeteoBCN

on:
  schedule:
    - cron: '0 8 * * *'   # 09:00 Spain Time
    - cron: '0 13 * * *'  # 16:00 Spain Time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librer√≠as
        run: |
          pip install pandas requests joblib scikit-learn lxml

      - name: Ejecutar Pipeline Backend
        run: python app_prediccion.py

      - name: Guardar cambios (Commit & Push)
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add data/training_datasets/*.csv
          git add data/model_memory/*.pkl
          git commit -m "ü§ñ MLOps: Actualizaci√≥n autom√°tica" || echo "‚ö†Ô∏è Sin cambios"
          git pull --rebase
          git push